### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by amitnigam** [evershopcommerce/evershop#177]
Running npm run build fails with following stack trace :
 ERROR in ./node_modules/@evershop/evershop/src/lib/components/react/server/render.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Cannot find module '@babel/core'
  Require stack:
  - /Users/../Projects/my-app/node_modules/babel-loader/lib/index.js
  - /Users/../Projects/my-app/node_modules/loader-runner/lib/loadLoader.js
  - /Users/../Projects/my-app/node_modules/loader-runner/lib/LoaderRunner.js
  - /Users/../Projects/my-app/node_modules/webpack/lib/NormalModuleFactory.js
  - /Users/../Projects/my-app/node_modules/webpack/lib/Compiler.js
  - /Users/../Projects/my-app/node_modules/webpack/lib/webpack.js
  - /Users/../Projects/my-app/node_modules/webpack/lib/index.js
  - /Users/../Projects/my-app/node_modules/@evershop/evershop/bin/build/complie.js
  - /Users/../Projects/my-app/node_modules/@evershop/evershop/bin/build/index.js
  - /Users/../Projects/my-app/node_modules/@evershop/evershop/bin/evershop
   babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:101:18)
      at Object.<anonymous> (/Users/../Projects/my-app/node_modules/babel-loader/lib/index.js:7:11)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:12)
      at Module.require (internal/modules/cjs/loader.js:974:19)

  Server (webpack 5.75.0) compiled with 40 errors in 636 ms
Unhandled Rejection at: Promise  Promise { <rejected> null }  reason:  null

**Comment by treoden** [comment]
Hi @amitnigam,
Are using cloning the source from Github repo? Did you run the command "npm install" to install the dependencies?

Thanks

**Comment by amitnigam** [comment]
@treoden I ran npx create-evershop-app my-app --playAround and then npm run build. I just tried npm install, as well that too didn't work. I have checked out source as well from GitHub. I can try building from source too. but wanted to try playAround first. Can you please advise what could be the steps for building from source.

**Comment by treoden** [comment]
Thanks @amitnigam ,

Can you please check what is the version of your npm? "npm -v" can tell.
