### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by Antoineofficiel** [evershopcommerce/evershop#262]
I have an error here from the github files

root@ShipHive:/var/www/html/evershop# npm run setup

> evershop@1.0.0-beta setup
> evershop install

/var/www/html/evershop/packages/evershop/bin/install/migrate.js:81
      email: adminUser?.email || 'demo@demo.com',
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/html/evershop/packages/evershop/bin/install/index.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by treoden** [comment]
Hi @Antoineofficiel ,

What is your node version. I think you are using <14.0 version
Thanks
