### ISSUE TITLE
npm run user:create -- --email "your email" --password "your password" --name "your name"

### ISSUE THREAD

**Issue by khanh-huynh-1986** [evershopcommerce/evershop#369]
cannot be replaced and returns a value
> evershop@1.0.0-beta user:create
> evershop user:create --name name --email email --password password

Options:
      --version   Show version number                                  [boolean]
  -n, --name      Admin user full name                       [string] [required]
  -e, --email     User email                                 [string] [required]
  -p, --password  User password                              [string] [required]
      --help      Show help                                            [boolean]

Invalid password

**Comment by treoden** [comment]
Hi @khanh-huynh-1986 ,

Make sure you password is secure. It contains at least 1 uppercase, 1 lower case, 1 number and 1 special character 

Thanks

**Comment by khanh-huynh-1986** [comment]
After setting the password correctly, it says something like this:
❌ AggregateError
    at C:\xampp\htdocs\my-app\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertOnUpdateQuery.sql (C:\xampp\htdocs\my-app\packages\postgres-query-builder\index.js:911:20)
    at async InsertOnUpdateQuery.execute (C:\xampp\htdocs\my-app\packages\postgres-query-builder\index.js:513:15)
    at async InsertOnUpdateQuery.execute (C:\xampp\htdocs\my-app\packages\postgres-query-builder\index.js:967:18)
    at async createAdminUser (C:\xampp\htdocs\my-app\packages\evershop\bin\user\create.js:61:5)


I am new, please help me how to solve the above problem. Thank you very much!

**Comment by treoden** [comment]
Hi @khanh-huynh-1986 ,

Did you manage to install the app? 
Can you provide the system information like Node version, Postgres version, npm version?

Thanks

**Comment by khanh-huynh-1986** [comment]
- HP@Khanh-Huynh MINGW64 /c/xampp/htdocs/my-app
$ node --version
v21.0.0
- Postgres:16.0
- $ npm --version
10.2.1
THanks!
