### ISSUE TITLE
[BUG] Creating an extension for product comment following the tutorial

### ISSUE THREAD

**Issue by rgchan2004** [evershopcommerce/evershop#462]
Following your step to create an extension for product comment, 
I have the following errors :
Using vscode to run development config, i have the following error, when clicking the product 

TypeError: Cannot read properties of undefined (reading 'getInfrastructureLogger')
    at wdm (C:\GitHub\EvershopWeb\my-app\node_modules\webpack-dev-middleware\dist\index.js:203:22)
    at C:\GitHub\EvershopWeb\my-app\node_modules\@evershop\evershop\bin\lib\addDefaultMiddlewareFuncs.js:252:54        
    at Layer.handle [as handle_request] (C:\GitHub\EvershopWeb\my-app\node_modules\express\lib\router\layer.js:95:5)   
    at trim_prefix (C:\GitHub\EvershopWeb\my-app\node_modules\express\lib\router\index.js:328:13)
    at C:\GitHub\EvershopWeb\my-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\GitHub\EvershopWeb\my-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\GitHub\EvershopWeb\my-app\node_modules\express\lib\router\index.js:280:10)
    at C:\GitHub\EvershopWeb\my-app\node_modules\@evershop\evershop\bin\lib\addDefaultMiddlewareFuncs.js:229:14        
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version
 - Postgres Version
 - EverShop Version
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by vitran96** [comment]
@rgchan2004 Evershop has updated since then and the tutorial is updated.
Could you try again, please?
I also have an issue when following the tutorial (issue here: https://github.com/evershopcommerce/docs/issues/18)
I think the actual working code for the tutorial can be found in the source code: https://github.com/evershopcommerce/evershop/tree/dev/packages/product_review
