### ISSUE TITLE
[BUG] query.and is not a function

### ISSUE THREAD

**Issue by leandrosantoss** [evershopcommerce/evershop#573]
**Describe the bug**
When finalizing the purchase, you need the order_created and order_placed events, but the error below was displayed.

Uncaught TypeError TypeError: query.and is not a function
    at loadEvents (c:\Users\lpdsa\Documents\Projetos\SquidTech\Git\ecommerce\node_modules\@evershop\evershop\src\lib\event\event-manager.js:73:11)
    at <anonymous> (c:\Users\lpdsa\Documents\Projetos\SquidTech\Git\ecommerce\node_modules\@evershop\evershop\src\lib\event\event-manager.js:38:29)
    at listOnTimeout (internal/timers:573:17)
    at processTimers (internal/timers:514:7)

**Expected behavior**
I need the events (order_created and order_placed). The event was not generated

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/59751373/55fb6f9a-d7b0-4a31-85f7-ee5470fadb75)

![image](https://github.com/evershopcommerce/evershop/assets/59751373/73fe8254-31e3-4d0a-acd6-b48e80e6f266)

**Background (please complete the following information):**
 - NodeJS 20
 - EverShop 1.1.0

**Comment by leandrosantoss** [comment]
Hi @treoden 

I believe it should be
`query.andWhere('uuid', 'NOT IN', [])
`
Not?
