### ISSUE TITLE
[BUG] AggregateError [ECONNREFUSED]:

### ISSUE THREAD

**Issue by slim-python** [evershopcommerce/evershop#582]
**Describe the bug**
when i tried to run it locally in windows 11, i got the following error after npm run setup

D:\kode\OSS\evershop>npm run setup

> evershop@1.0.0-beta setup
> evershop install

WARNING: No configurations found in configuration directory:D:\kode\OSS\evershop\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
√ Postgres Database Host (localhost) · localhost

√ Postgres Database Port (5432) · 5432
√ Postgres Database Name (evershop) · evershop
√ Postgres Database User (postgres) · postgres
√ PostgreSQL Database Password (<empty>) ·
❌ error: 

AggregateError [ECONNREFUSED]:
    at D:\kode\OSS\evershop\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async install (D:\kode\OSS\evershop\packages\evershop\bin\install\index.js:108:5)
    at async D:\kode\OSS\evershop\packages\evershop\bin\install\index.js:287:5

**To Reproduce**
clone repo and do npm install and then do npm run setup

**Expected behavior**
should have worked but did'nt

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version
 - Postgres Version
 - EverShop Version
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by treoden** [comment]
Hi @slim-python 

Please tell us about your env, node version, postgres version ...etc

**Comment by chinhquoc01** [comment]
Same error here. Happend on npm version 10.2.3, node 20.10.0, postgres 16.4

**Comment by chinhquoc01** [comment]
> Same error here. Happend on npm version 10.2.3, node 20.10.0, postgres 16.4

Turned out that my postgresql run on port 5433, but evershop setup postgresql run default on port 5432. Just change the port config and everything is okay.
