### ISSUE TITLE
[BUG] Database not being written to, images not showing and url rewrite not working

### ISSUE THREAD

**Issue by ogmaxbone** [evershopcommerce/evershop#592]
[mulligans] [2024-08-12 22:20:50] Node.js v20.16.0
[mulligans] [2024-08-12 22:21:30] ❌ error: 
[mulligans] [2024-08-12 22:21:30] remaining connection slots are reserved for roles with the SUPERUSER attribute
[mulligans] [2024-08-12 22:21:30] error: remaining connection slots are reserved for roles with the SUPERUSER attribute
[mulligans] [2024-08-12 22:21:30]     at /workspace/node_modules/pg-pool/index.js:45:11
[mulligans] [2024-08-12 22:21:30]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[mulligans] [2024-08-12 22:21:30]     at async getConnection (/workspace/node_modules/@evershop/postgres-query-builder/index.js:1073:10)
[mulligans] [2024-08-12 22:21:30]     at async SelectQuery.execute (/workspace/node_modules/@evershop/postgres-query-builder/index.js:638:20)
[mulligans] [2024-08-12 22:21:30]     at async TaxClassCollection.items (/workspace/node_modules/@evershop/evershop/src/modules/tax/services/TaxClassCollection.js:44:19)
[mulligans] [2024-08-12 22:21:30]     at async Promise.all (index 0)
[mulligans] [2024-08-12 22:21:30]     at async Promise.all (index 24)
[mulligans] [2024-08-12 22:21:30]     at async graphql (/workspace/node_modules/@evershop/evershop/src/modules/graphql/pages/global/[buildQuery]graphql[notification].js:50:24)
[mulligans] [2024-08-12 22:21:30]     at async asyncMiddlewareWrapper (/workspace/node_modules/@evershop/evershop/src/lib/middleware/async.js:35:5)
[mulligans] [2024-08-12 22:21:34] ❌ error: 
[mulligans] [2024-08-12 22:21:34] remaining connection slots are reserved for roles with the SUPERUSER attribute
[mulligans] [2024-08-12 22:21:34] error: remaining connection slots are reserved for roles with the SUPERUSER attribute
[mulligans] [2024-08-12 22:21:34]     at /workspace/node_modules/pg-pool/index.js:45:11
[mulligans] [2024-08-12 22:21:34]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[mulligans] [2024-08-12 22:21:34]     at async getConnection (/workspace/node_modules/@evershop/postgres-query-builder/index.js:1073:10)
[mulligans] [2024-08-12 22:21:34]     at async SelectQuery.execute (/workspace/node_modules/@evershop/postgres-query-builder/index.js:638:20)
[mulligans] [2024-08-12 22:21:34]     at async AttributeGroupCollection.items (/workspace/node_modules/@evershop/evershop/src/modules/catalog/services/AttributeGroupCollection.js:85:19)
[mulligans] [2024-08-12 22:21:34]     at async Promise.all (index 0)
[mulligans] [2024-08-12 22:21:34]   
![Screenshot 2024-08-12 at 6 32 38 PM](https://github.com/user-attachments/assets/9ca360df-10b7-4441-9382-91a5d63d4b22)
  at async Promise.all (index 16)
[mulligans] [2024-08-12 22:21:34]     at async graphql (/workspace/node_modules/@evershop/evershop/src/modules/graphql/pages/global/[buildQuery]graphql[notification].js:50:24)

deployed to digital ocean via app platform

PostgreSQL 16

**Comment by ogmaxbone** [comment]
if i rebuild and refresh db connections it works again. multiple people login to the same admin account, could that be it?
